Notes for CI section of tutorial
martinagvilas/jupytercon_tutorial pull request #1
Opened 2020-09-03 19:45 UTC by sgibson91

2020-09-14 09:14 UTC, martinagvilas requested changes
This is great! 

I guess the next step would be to answer the question:` "how can we use CI (or github actions) with jupyter-books?"` I was thinking there might be two possibilities:

1) We create a separate section dealing with this topic, after the text you wrote here
2) We interleave these questions with the text here. For example, under the question `"What is continuous integration?"` we can add a bulletpoint stating for what we would need continuous integration specifically in jupyter-books (e.g. make sure there are no syntax errors in the text, links are not broken, code cells have no bugs, etc), or under the question `"What is continuous deployment?"` we could add that in this case it might be useful to deploy a preview of the book after each change.

2020-09-14 09:14 UTC, martinagvilas commented on notes/ci_cd.md
> +A version control system is the crux of CI processes and is often supplemented with other checks such as code quality, syntax style reviews, and more.
I would replace the word `crux` from this sentence since its meaning might be not straightforward for non-native English speakers (or at least that was my case 😆 ). Maybe something like `the crucial element`?

2020-09-14 09:14 UTC, martinagvilas commented on notes/ci_cd.md
> +
Maybe its worth to add some examples of CI vendors here, besides github actions?

2020-09-14 09:18 UTC, martinagvilas commented
Also, we should link somewhere on this text (or what will be added) the explanation to jupyter-book and github actions integration that the jupyter-book tutorials already have (see [here](https://jupyterbook.org/publish/gh-pages.html#automatically-host-your-book-with-github-actions)).

2020-09-16 18:38 UTC, sgibson91 commented on notes/ci_cd.md
> +A version control system is the crux of CI processes and is often supplemented with other checks such as code quality, syntax style reviews, and more.
Done in 4128569

2020-09-16 18:38 UTC, sgibson91 commented on notes/ci_cd.md
> +
Done in 1db7011

2020-09-16 19:26 UTC, sgibson91 commented
> 2. We interleave these questions with the text here. For example, under the question `"What is continuous integration?"` we can add a bulletpoint stating for what we would need continuous integration specifically in jupyter-books (e.g. make sure there are no syntax errors in the text, links are not broken, code cells have no bugs, etc), or under the question `"What is continuous deployment?"` we could add that in this case it might be useful to deploy a preview of the book after each change.

Went for this option in 5b96358

2020-09-17 08:08 UTC, martinagvilas approved these changes

2020-09-17 08:09 UTC, martinagvilas commented
Awesome! Should we merge or do you want add something else to this PR?

2020-09-17 08:21 UTC, sgibson91 commented
I was thinking I might add an example of a GHA workflow file?

2020-09-17 08:47 UTC, martinagvilas commented
@sgibson91 sounds good! 

We also need to create the part of the tutorial where people build the book in their own repo (using a github action I guess). I was planning to do this later today, and we can link to these notes from that part right?

2020-09-17 08:48 UTC, sgibson91 commented
Yeah, this would be a good introduction to that part!

2020-09-18 12:47 UTC, sgibson91 commented
I think I won't merge this particular PR and instead move the content into the empty Notebook. @martinagvilas which is the best branch for me to branch off of and do that?

2020-09-18 13:05 UTC, martinagvilas commented
I think the branch `module-3` is the most up-to-date 🚀

2020-09-18 13:42 UTC, closed without merging